export const FETCH_INGREDIENTS="FETCH_INGREDIENTS"
export const FETCH_INGREDIENTS_STATE="FETCH_INGREDIENTS_STATE"

export const GET_CONSTRUCTOR="GET_CONSTRUCTOR"

export const ADD_INGREDIENT_DETAILS="ADD_INGREDIENT_DETAILS"
export const DELETE_INGREDIENT_DETAILS="DELETE_INGREDIENT_DETAILS"

export const FETCH_ORDER="FETCH_ORDER"

export const IS_MODAL_OPEN="IS_MODAL_OPEN"
