export const FETCH_INGREDIENTS_REQUEST : "FETCH_INGREDIENTS_REQUEST" = "FETCH_INGREDIENTS_REQUEST"
export const FETCH_INGREDIENTS_SUCCESS : "FETCH_INGREDIENTS_SUCCESS" = "FETCH_INGREDIENTS_SUCCESS"
export const FETCH_INGREDIENTS_ERROR : "FETCH_INGREDIENTS_ERROR" = "FETCH_INGREDIENTS_ERROR"

export const FETCH_ORDER_REQUEST : "FETCH_ORDER_REQUEST" = "FETCH_ORDER_REQUEST"
export const FETCH_ORDER_SUCCESS : "FETCH_ORDER_SUCCESS" = "FETCH_ORDER_SUCCESS"
export const FETCH_ORDER_ERROR : "FETCH_ORDER_ERROR" = "FETCH_ORDER_ERROR"

export const SET_CONSTRUCTOR : "SET_CONSTRUCTOR" = "SET_CONSTRUCTOR"
export const CLEAN_CONSTRUCTOR : "CLEAN_CONSTRUCTOR" = "CLEAN_CONSTRUCTOR"

export const SET_CURRENT_INGREDIENT : "SET_CURRENT_INGREDIENT" = "SET_CURRENT_INGREDIENT"
export const CLEAN_CURRENT_INGREDIENT : "CLEAN_CURRENT_INGREDIENT" = "CLEAN_CURRENT_INGREDIENT"

export const OPEN_MODAL : "OPEN_MODAL" = "OPEN_MODAL"
export const CLOSE_MODAL : "CLOSE_MODAL" = "CLOSE_MODAL"

export const FETCH_USER_REQUEST : "FETCH_USER_REQUEST" = "FETCH_USER_REQUEST"
export const FETCH_USER_SUCCESS : "FETCH_USER_SUCCESS" = "FETCH_USER_SUCCESS"
export const FETCH_USER_ERROR : "FETCH_USER_ERROR" = "FETCH_USER_ERROR"

export const AUTH_CHECKED : "AUTH_CHECKED" = "AUTH_CHECKED"

export const FETCH_FEED_REQUEST : "FETCH_FEED_REQUEST" = "FETCH_FEED_REQUEST"
export const FETCH_FEED_SUCCESS : "FETCH_FEED_SUCCESS" = "FETCH_FEED_SUCCESS"
export const FETCH_FEED_ERROR : "FETCH_FEED_ERROR" = "FETCH_FEED_ERROR"

export const FETCH_USER_FEED_REQUEST : "FETCH_USER_FEED_REQUEST" = "FETCH_USER_FEED_REQUEST"
export const FETCH_USER_FEED_SUCCESS : "FETCH_USER_FEED_SUCCESS" = "FETCH_USER_FEED_SUCCESS"
export const FETCH_USER_FEED_ERROR : "FETCH_USER_FEED_ERROR" = "FETCH_USER_FEED_ERROR"

