export const FETCH_INGREDIENTS_REQUEST : "FETCH_INGREDIENTS_REQUEST" = "FETCH_INGREDIENTS_REQUEST"
export const FETCH_INGREDIENTS_SUCCESS : "FETCH_INGREDIENTS_SUCCESS" = "FETCH_INGREDIENTS_SUCCESS"
export const FETCH_INGREDIENTS_ERROR : "FETCH_INGREDIENTS_ERROR" = "FETCH_INGREDIENTS_ERROR"

export const FETCH_ORDER_REQUEST : "FETCH_ORDER_REQUEST" = "FETCH_ORDER_REQUEST"
export const FETCH_ORDER_SUCCESS : "FETCH_ORDER_SUCCESS" = "FETCH_ORDER_SUCCESS"
export const FETCH_ORDER_ERROR : "FETCH_ORDER_ERROR" = "FETCH_ORDER_ERROR"

export const SET_CONSTRUCTOR : "SET_CONSTRUCTOR" = "SET_CONSTRUCTOR"
export const CLEAN_CONSTRUCTOR : "CLEAN_CONSTRUCTOR" = "CLEAN_CONSTRUCTOR"

export const SET_CURRENT_INGREDIENT : "SET_CURRENT_INGREDIENT" = "SET_CURRENT_INGREDIENT"
export const CLEAN_CURRENT_INGREDIENT : "CLEAN_CURRENT_INGREDIENT" = "CLEAN_CURRENT_INGREDIENT"

export const OPEN_MODAL : "OPEN_MODAL" = "OPEN_MODAL"
export const CLOSE_MODAL : "CLOSE_MODAL" = "CLOSE_MODAL"

export const FETCH_USER_REQUEST : "FETCH_USER_REQUEST" = "FETCH_USER_REQUEST"
export const FETCH_USER_SUCCESS : "FETCH_USER_SUCCESS" = "FETCH_USER_SUCCESS"
export const FETCH_USER_ERROR : "FETCH_USER_ERROR" = "FETCH_USER_ERROR"

export const AUTH_CHECKED : "AUTH_CHECKED" = "AUTH_CHECKED"

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_GET_ORDERS: 'WS_GET_ORDERS' = 'WS_GET_ORDERS';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';
export const WS_SEND_PONG: 'WS_SEND_PONG' = 'WS_SEND_PONG';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_CONNECTION_END: 'WS_CONNECTION_END' = 'WS_CONNECTION_END';

export type TActions = typeof FETCH_INGREDIENTS_REQUEST |
typeof FETCH_INGREDIENTS_SUCCESS |
typeof FETCH_INGREDIENTS_ERROR |
typeof FETCH_ORDER_REQUEST |
typeof FETCH_ORDER_SUCCESS |
typeof FETCH_ORDER_ERROR |
typeof SET_CONSTRUCTOR |
typeof CLEAN_CONSTRUCTOR |
typeof SET_CURRENT_INGREDIENT |
typeof CLEAN_CURRENT_INGREDIENT |
typeof OPEN_MODAL |
typeof CLOSE_MODAL |
typeof FETCH_USER_REQUEST |
typeof FETCH_USER_SUCCESS |
typeof FETCH_USER_ERROR |
typeof AUTH_CHECKED |
typeof WS_CONNECTION_START |
typeof WS_CONNECTION_SUCCESS |
typeof WS_GET_ORDERS |
typeof WS_SEND_MESSAGE |
typeof WS_SEND_PONG |
typeof WS_CONNECTION_ERROR |
typeof WS_CONNECTION_CLOSED |
typeof WS_CONNECTION_END;
